### PR TITLE
Fix statement response

### LINKED ISSUE #916: bug docker image path
i specified `"spark.kubernetes.container.image"` in `LIGHTER_SESSION_DEFAULT_CONF` , but the juypter notebook can't identify it. in order to work, i need to insert this key in `%%configure` jupyter notebook. Also tested with latest docker image `0.1.0-spark3.5.0` and `0.0.50-spark3.5.0`.   Does `LIGHTER_SESSION_DEFAULT_CONF` key work on latest version of lighter?

### PR DESCRIPTION
**Pull request by pdambrauskas**
fixes #916

### CODE REVIEW

**Review by Minutis — APPROVED** [review]

**Comment by pdambrauskas** [comment]
@cometta can you try ghcr.io/exacaster/lighter:919-spark3.5.1, looks like we had one dependency missing. I guess we need to do more testing before releasing, 0.1.0 seems to have quite a few problems :(.

**Pull request merged**
